[project]
name = "jobportalflaskapp"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
//wesd=employer registered company apple inc.,ret=seeker,gauri=seeker